### PR TITLE
Translation Updates

### PR DESCRIPTION
**Pull request by Grey41**
Very useful meeting timer! It always works perfectly. I noticed that there were some changes in the talk names and translations. Now we have gems but without the digging.

### CODE REVIEW

**Comment by AntonyCorbett** [comment]
@Grey41 Thanks for highlighting the need for this update. As explained in the project's Contributing guidelines, all changes to the resource localisations are made in the **Crowdin** platform. These are then automatically merged into the repo. I will make the change in the native (English) resource and then make individual changes to the various languages using the changes you have provided,

**Comment by Grey41** [comment]
I see! I should've read the guidelines properly. I'll close this PR for now.

**Comment by AntonyCorbett** [comment]
@Grey41 no problem. Thanks for looking up all of the translations!

**Comment by AntonyCorbett** [comment]
@Grey41 - I've transferred your translations to Crowdin. They should sync with the main repo shortly. Thanks again!

**Comment by Grey41** [comment]
Thank you! I'm glad it helped.

**Pull request closed without merging**
