### PR TITLE
Update GreenYellowRedSelector.cs

### PR DESCRIPTION
**Pull request by jericusdegamuz**
Changes to yellow with one minute remaining. Recommended for Assembly or Convention use.

Thanks for sending a pull request! Please review the [guidelines for contributing](CONTRIBUTING.md), then fill out the blanks below.

What does this implement/fix? Explain your changes
--------------------------------------------------
Instead of 30 seconds, color changes to yellow with 60 seconds remaining. This setup is recommended for Assembly or Convention use.

Does this close any currently open issues?
------------------------------------------
…

Any other comments?
-------------------
…

### CODE REVIEW

**Comment by AntonyCorbett** [comment]
Thanks for your PR. The change would break the current behaviour. At the very least, I suggest this would need to be implemented as a user-defined option with a default of 30 seconds.

**Comment by AntonyCorbett** [comment]
@jericusdegamuz A neat implementation would be to add a duration attribute called "closing" (or similar) to the file-based schedule items. This would allow you to specify a bespoke value for each item. The "auto" implementation would remain unchanged.

**Comment by AntonyCorbett** [comment]
@jericusdegamuz I've created a new pre-release which includes the "closingSecs" attribute for file-based mode (as used in assemblies). You should be able to add this attribute to talks in your xml file to change the duration to "60".

**Comment by jericusdegamuz** [comment]
Thank you very much brother. This will benefit those who needs this feature.

By the way, for our assembly last week, I downloaded your source code on
GitHub, modified the GreenYellowRedSelector.cs to 60 seconds, compiled it
as an installer, and installed it on the laptop used for the timer. It
worked perfectly!

Backstory: Our CO asked me to have a timer that "counts up, background
color turns yellow with 1 minute remaining, background color turns red on
overtime and will continue to count up until stopped." I tried making a
web-based version but cant make it accurate; there are lags. I used my
custom OnlyT which worked fine, the CO didn't mind that the font changes
color, not the background, maybe in your future updates. Thanks again for
your help.

**Pull request closed without merging**
