### PR TITLE
Add timers web page

### PR DESCRIPTION
**Pull request by DavidIQ**
What does this implement/fix? Explain your changes
--------------------------------------------------
Implements a timers web page similar to what is shown on the mobile apps.
Mid-week meeting:
image

Weekend meeting:
image

Does this close any currently open issues?
------------------------------------------
No.

Any other comments?
-------------------
Would appreciate some feedback/guidance on preferred direction.

### CODE REVIEW

**Comment by DavidIQ** [comment]
So I'm not done with this as there is styling work still to be done, but want to make sure on some of the choices and approaches made to make sure you're OK with them. Otherwise they can be reworked.

**Comment by AntonyCorbett** [comment]
@DavidIQ thanks - great idea and nicely worked. Let me know if you want me to merge this PR or wait for another.

**Comment by DavidIQ** [comment]
Going to continue working on the HTML and CSS to get it in a more presentable state, especially for the mid-week meeting, and then I'll remove the WIP. Thanks!

**Comment by DavidIQ** [comment]
This is good to go now. 😅

**Comment by AntonyCorbett** [comment]
> 
> 
> This is good to go now. 😅

Thank you David - I've made a note to review and merge on Friday.

**Comment by DavidIQ** [comment]
Done. Will probably send a pr at some point to modernize the clock page so it uses current web standards to making it responsive.

**Comment by AntonyCorbett** [comment]
@DavidIQ Do you still use the "Timers" web page in OnlyT? I've just come to look at it and the page always shows "offline". I'm wondering if something broke it recently and I didn't spot it.

**Comment by AntonyCorbett** [comment]
@DavidIQ Sorry, ignore the previous message. I forgot to turn on "remote apps"

**Comment by DavidIQ** [comment]
No problem @AntonyCorbett and yes we still use the timers page, at least those of us in our congregation that know how to get to it (even though I've shared the link numerous times). :)

**Pull request merged**
